language: objective-c
osx_image: xcode12.0
rvm:
- 2.2         #see before_install for getting RVM stable.

before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh

install:
./Scripts/install.sh

script:
- ./Scripts/build.sh
