language: objective-c
sudo: required
osx_image: xcode9.4


before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/runtests.sh
- chmod a+x ./Scripts/export-unity-package.sh

install:
- ./Scripts/install.sh

script:
- ./Scripts/build.sh
- ./Scripts/runtests.sh
