language: objective-c
osx_image: xcode9.4
rvm:
- 2.2         #see before_install for getting RVM stable.

cache:
    directories:
      - $UNITY_DOWNLOAD_CACHE

before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/export-unity-package.sh

install:
- ./Scripts/install.sh

script:
- ./Scripts/build.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: $DEPLOY_UNITYPACKAGE
    skip_cleanup: true
    overwrite: true
    on:
    tags: true 