language: objective-c
sudo: required
osx_image: xcode9.4


env:
    global:
      - UNITY_PROJECT_DIR=/Users/travis/build/alan-turing-institute/Unity-ci-travis/

before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/runtests.sh
- chmod a+x ./Scripts/export-unity-package.sh

install:
- ./Scripts/install.sh

script:
- ./Scripts/build.sh
- ./Scripts/runtests.sh
